In [1]:
import pandas as pd

df_classes = pd.read_csv("../ART_Classification/wikiArt/classes.csv")

In [2]:
df_classes.head()

,filename,artist,genre,description,phash,width,height,genre_count,subset
0,Abstract_Expressionism/aaron-siskind_acolman-1...,aaron siskind,['Abstract Expressionism'],acolman-1-1955,bebbeb018a7d80a8,1922,1382,1,train
1,Abstract_Expressionism/aaron-siskind_chicago-6...,aaron siskind,['Abstract Expressionism'],chicago-6-1961,d7d0781be51fc00e,1382,1746,1,train
2,Abstract_Expressionism/aaron-siskind_glouceste...,aaron siskind,['Abstract Expressionism'],gloucester-16a-1944,9f846e5a6c639325,1382,1857,1,train
3,Abstract_Expressionism/aaron-siskind_jerome-ar...,aaron siskind,['Abstract Expressionism'],jerome-arizona-1949,a5d691f85ac5e4d0,1382,1849,1,train
4,Abstract_Expressionism/aaron-siskind_kentucky-...,aaron siskind,['Abstract Expressionism'],kentucky-4-1951,880df359e6b11db1,1382,1625,1,train

In [3]:
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

import os

import math

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

from sklearn.metrics import *

from tqdm.notebook import tqdm




N_TOP = 25

df = df_classes.groupby(["subset","artist"]).size().reset_index()
df.columns = ["subset", "artist", "size"]
df = df.pivot(index="artist",columns="subset", values="size")
df = df.reset_index()
df = df.fillna(0).sort_values(by="train", ascending=False)
df["train"] = df["train"].astype(np.int16)
df["test"] = df["test"].astype(np.int16)
df["uncertain artist"] = df["uncertain artist"].astype(np.int16)

df=df.sort_values(by="train", ascending=False)

top_artists = df["artist"].values[:N_TOP]
display(df.head(N_TOP))

df_all = df_classes[df_classes["artist"].isin(top_artists)].reset_index(drop = True)
le = LabelEncoder()
df_all["artist_class"] = le.fit_transform(df_all["artist"].values)
class_names = le.classes_

    
    
df_train = df_all.query("subset == 'train'").reset_index(drop = True)
df_test = df_all.query("subset == 'test'").reset_index(drop = True)


df_train, df_valid, y_train, y_valid =  train_test_split(df_train, df_train["artist"], 
                                                                   test_size=0.2, random_state=42, 
                                                                   stratify=df_train["artist"])


print(f"train:{df_train.shape[0]}, valid:{df_valid.shape[0]}, test:{df_test.shape[0]}")

/Users/kimsoyeon/opt/anaconda3/envs/torch-gpu/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

subset                 artist  test  train  uncertain artist
1074         vincent van gogh   378   1510                 0
809          nicholas roerich   363   1453                 0
898     pierre auguste renoir   280   1117                 2
190              claude monet   267   1067                 0
917        pyotr konchalovsky   185    739                 0
158          camille pissarro   177    707                 0
34             albrecht durer   166    662                 0
599       john singer sargent   157    625                 1
932                 rembrandt   155    621                 0
719              marc chagall   153    612                 0
846             pablo picasso   153    610                 0
420              gustave dore   151    602                 0
148           boris kustodiev   127    506                 0
252               edgar degas   122    487                 2
859              paul cezanne   116    463                 0
495           ivan aivazovsky   116    461                 0
749           martiros saryan   115    461                 0
289             eugene boudin   111    444                 0
180             childe hassam   110    437                 0
476                ilya repin   108    431                 0
504             ivan shishkin   104    416                 0
929          raphael kirchner   103    413                 0
448             henri matisse    98    393                 0
978             salvador dali    96    385                 0
157             camille corot    96    381                 1

train:12802, valid:3201, test:4007

In [4]:
df_train=df_train.reset_index().reset_index().rename({"index":"id"})

In [5]:
df_train=df_train.drop(labels="index",axis=1)

In [6]:
df_train.rename(columns={"level_0":"index"},inplace=True)

In [7]:
df_train.head()

,index,filename,artist,genre,description,phash,width,height,genre_count,subset,artist_class
0,0,Impressionism/edgar-degas_dancer-in-her-dressi...,edgar degas,['Impressionism'],dancer-in-her-dressing-room-1,cb9b01f0ca8f3ccc,1382,2137,1,train,6
1,1,Realism/camille-corot_l-arbre-tordu-les-chenes...,camille corot,['Realism'],l-arbre-tordu-les-chenes-du-mont-usey-fontaine...,f6f6c5921a996905,1792,1382,1,train,2
2,2,Impressionism/camille-pissarro_entrance-to-the...,camille pissarro,['Impressionism'],entrance-to-the-village-of-voisins-yvelines-1872,cbcf5960b2b8b514,1653,1382,1,train,3
3,3,Expressionism/henri-matisse_still-life-6.jpg,henri matisse,['Expressionism'],still-life-6,f1994d96b0316bc9,1382,2123,1,train,9
4,4,Symbolism/nicholas-roerich_mongolia-campaign-o...,nicholas roerich,['Symbolism'],mongolia-campaign-of-genghis-khan,a0dfd0a196e3e4b2,1845,1382,1,train,16

In [8]:
df_test.head()

,filename,artist,genre,description,phash,width,height,genre_count,subset,artist_class
0,Abstract_Expressionism/henri-matisse_blue-nude...,henri matisse,['Abstract Expressionism'],blue-nude-1952,afbcd133d0ccc069,1382,1769,1,test,9
1,Abstract_Expressionism/henri-matisse_blue-nude...,henri matisse,['Abstract Expressionism'],blue-nude,ff58d824d109cc6e,1382,2145,1,test,9
2,Abstract_Expressionism/henri-matisse_cut-outs-...,henri matisse,['Abstract Expressionism'],cut-outs-1,b2cf336117ca8713,2092,1382,1,test,9
3,Abstract_Expressionism/henri-matisse_cut-outs.jpg,henri matisse,['Abstract Expressionism'],cut-outs,bff3c8b6c0c9c08c,2082,1382,1,test,9
4,Abstract_Expressionism/henri-matisse_la-gerbe-...,henri matisse,['Abstract Expressionism'],la-gerbe-1953,acbccdc290b3db05,1675,1382,1,test,9

In [9]:
def get_data(df):
    ds_path = "../ART_Classification/wikiArt/"
    filenames = [ f"{ds_path}/{filename}" for filename in  df["filename"].values]
    labels = [artist for artist in df["artist_class"]]
    #ds = tf.data.Dataset.from_tensor_slices((filenames, labels))
    #return ds
    return filenames,labels

In [10]:
train_img_paths, train_labels = get_data(df_train)
val_img_paths, val_labels = get_data(df_valid)
test_img_paths, test_labels = get_data(df_test)

In [11]:
import random
import pandas as pd
import numpy as np
import os
import cv2
import time
import datetime

from sklearn import preprocessing
from sklearn.model_selection import train_test_split

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader

from tqdm.auto import tqdm

import albumentations as A
from albumentations.pytorch.transforms import ToTensorV2

import torchvision.models as models

from sklearn.metrics import f1_score
import matplotlib.pyplot as plt

import warnings


class CustomDataset(Dataset):
    def __init__(self, img_paths, labels, transforms=None):
        self.img_paths = img_paths
        self.labels = labels
        self.transforms = transforms

    def __getitem__(self, index):
        img_path = self.img_paths[index]
        image = cv2.imread(img_path)
        image = np.array(image)
        #image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        
        if self.transforms is not None:
            image = self.transforms(image=image)['image']
        
        if self.labels is not None:
            label = self.labels[index]
            return image, label
        else:
            return image
    
    def __len__(self):
        return len(self.img_paths)

In [12]:
CFG = {
    'IMG_SIZE':224,
    'BATCH_SIZE':16,
    'SEED':41
}

In [13]:
train_transform = A.Compose([
                            A.Resize(CFG['IMG_SIZE']*2,CFG['IMG_SIZE']*2),
                            A.RandomCrop(CFG['IMG_SIZE'],CFG['IMG_SIZE']),
                            A.HorizontalFlip(p=0.5),
                            A.VerticalFlip(p=0.5),
                            A.ShiftScaleRotate(p=0.5),
                            A.OneOf([
                                A.CLAHE(clip_limit=2),
                                A.RandomBrightnessContrast(),
                            ], p=0.3),
                            A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225), max_pixel_value=255.0, always_apply=False, p=1.0),
                            ToTensorV2()
                            ])

val_transform = A.Compose([
                            A.Resize(CFG['IMG_SIZE']*2,CFG['IMG_SIZE']*2),
                            A.RandomCrop(CFG['IMG_SIZE'],CFG['IMG_SIZE']),
                            A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225), max_pixel_value=255.0, always_apply=False, p=1.0),
                            ToTensorV2()
                            ])

test_transform = A.Compose([
                            A.Resize(CFG['IMG_SIZE'],CFG['IMG_SIZE']),
                            A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225), max_pixel_value=255.0, always_apply=False, p=1.0),
                            ToTensorV2()
                            ])

In [27]:
train_dataset = CustomDataset(train_img_paths, train_labels, train_transform)
train_loader = DataLoader(train_dataset, batch_size = CFG['BATCH_SIZE'], shuffle=True, num_workers=0, pin_memory=True, drop_last=True)

val_dataset = CustomDataset(val_img_paths, val_labels, val_transform)
val_loader = DataLoader(val_dataset, batch_size=CFG['BATCH_SIZE'], shuffle=False, num_workers=0, pin_memory=True, drop_last=True)

In [28]:
#from torch.optim import lr_scheduler

model_ft = models.densenet121(pretrained=True)

for param in model_ft.parameters():
    param.requires_grad = True
    
num_ftrs = model_ft.classifier.in_features
# 또는, nn.Linear(num_ftrs, len (class_names))로 일반화할 수 있습니다.
model_ft.fc = nn.Linear(num_ftrs, 25)

#criterion = nn.CrossEntropyLoss()
# 모든 매개변수들이 최적화되었는지 관찰
#optimizer_ft = optim.SGD(model_ft.parameters(), lr=0.001, momentum=0.9)

# 7 에폭마다 0.1씩 학습률 감소
#exp_lr_scheduler = lr_scheduler.StepLR(optimizer_ft, step_size=7, gamma=0.1)

In [29]:
from torch.optim.optimizer import Optimizer

def eval_model(model_ft, data_loader, device):
  model_ft.eval()
  ys = []
  ypreds = []
  for x, y in data_loader:
    x = x.to(device)
    y = y.to(device)

    with torch.no_grad():
      _, y_pred = model_ft(x).max(1)
    ys.append(y)
    ypreds.append(y_pred)

  ys = torch.cat(ys)
  ypreds = torch.cat(ypreds)

  acc = (ys == ypreds).float().sum() / len(ys)
  return acc.item()


def train_model(model_ft,train_loader, val_loader, only_fc = True,
                optimizer_cls = optim.Adam,
                loss_fn = nn.CrossEntropyLoss(),
                n_iter=10, device='cpu'):
  train_losses = []
  train_acc = []
  val_acc = []

  if only_fc:
    optimizer = optimizer_cls(model_ft.fc.parameters())
  
  else:
    optimizer = optimizer_cls(model_ft.parameters())

  for epoch in range(n_iter):
    running_loss = 0.0
    model_ft.train()
    n = 0
    n_acc = 0

    for i, (xx, yy) in tqdm(enumerate(train_loader), 
                            total= len(train_loader)):
      yy = torch.from_numpy(np.asarray(yy))
      xx = xx.to(device)
      yy = yy.to(device)
      h = model_ft(xx)
      loss = loss_fn(h,yy)
      optimizer.zero_grad()
      loss.backward()
      optimizer.step()
      running_loss += loss.item()
      n += len(xx)
      _,y_pred = h.max(1)
      n_acc += (yy == y_pred).float().sum().item()

    train_losses.append(running_loss/i)
    
    train_acc.append(n_acc / n)

    val_acc.append(eval_model(model_ft, val_loader, device))

    print(epoch, train_losses[-1], train_acc[-1], val_acc[-1], flush = True)

In [ ]:
model_ft.to("mps")

train_model(model_ft, train_loader, val_loader, n_iter=10, device='mps')

  0%|          | 0/800 [00:00<?, ?it/s]

0 9.387040134663874 0.000546875 0.0012499999720603228

  0%|          | 0/800 [00:00<?, ?it/s]

1 9.370655262723883 0.00078125 0.0009374999790452421

  0%|          | 0/800 [00:00<?, ?it/s]

2 9.374305766873126 0.000390625 0.0009374999790452421

  0%|          | 0/800 [00:00<?, ?it/s]

3 9.38319562880954 0.00078125 0.0006249999860301614

  0%|          | 0/800 [00:00<?, ?it/s]

4 9.383038633009967 0.0003125 0.0

  0%|          | 0/800 [00:00<?, ?it/s]